services:
  vps2_core:
    container_name: windows-11-pro
    image: dockurr/windows
    environment:
      VERSION: 11
      USERNAME: "bill"
      PASSWORD: "gates"
      REGION: "en-US"
      KEYBOARD: "en-US"
    mem_limit: 16g
    restart: always
    build:
      dockerfile: ./Docker/Dockerfile
      context: .
    working_dir: /Application
    volumes:
      - .:/Application
      - mount:/mnt/Vps3/Mount
      - mount2:/mnt/Disk2
      - cdrom:/dev/cdrom
    tmpfs:
      - /tmp/raxon/org
    ports:
      - "8006:8006"
    networks:
      - raxon-org-network
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
volumes:
  mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Vps3/Mount
  mount2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Disk2
  cdrom:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dev/cdrom
networks:
  raxon-org-network:
    driver: bridge
